services:

  defect-searcher:
    build:
      context: ./app-data/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - C:\Users\Ilia\Desktop\GeoPix\results1:/application/results
    restart: always
    ports:
      - 0.0.0.0:8001:8000