services:

  image-matcher:
    build:
      context: ./app-data/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./layouts:/application/layouts
      - ./results:/application/results
    restart: always
    ports:
      - 0.0.0.0:8000:8000